### ISSUE TITLE
Teampass API still not working on docker container

### ISSUE THREAD

**Issue by CayoM** [nilsteampassnet/TeamPass#2502]
### Steps to reproduce
1. Use following docker-compose.yml file
```
version: "3"
services:
  teampass:
    image: teampass/teampass:latest
    restart: always
    environment:
      VIRTUAL_HOST: localhost
    networks:
      - frontend
      - backend
    volumes:
      - ./volumes/teampass:/var/www/html
    ports:
      - 80:80

  db:
    restart: always
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: teampass
      MYSQL_USER: teampass
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
  backend:
```

2. Configure minimal needed settings, enable API and create an apikey
3. Try to use the API
`http://localhost:80/api/index.php/info/version?apikey=<yourAPIkey>`

### Expected behaviour
I should get an json output

### Actual behaviour
all i get is:
```
teampass_1  | 10.0.2.2 - - [18/Dec/2018:15:55:58 +0000] "GET /api/index.php/info/version?apikey=GJasnRfkX8SY897S5xJ7CFuEM2HSYrR4yr48hde HTTP/1.1" 301 178 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
teampass_1  | 2018/12/18 15:56:39 [info] 28#28: *115 client closed connection while waiting for request, client: 10.0.2.2, server: 0.0.0.0:80
teampass_1  | 2018/12/18 15:56:39 [info] 28#28: *116 client closed connection while waiting for request, client: 10.0.2.2, server: 0.0.0.0:80
```

### Server configuration
**Operating system**: Docker-Container

**Web server:** Docker-Container

**Database:** Docker-Container

**PHP version:** Docker-Container

**Teampass version:** Docker-Container

**Teampass configuration file:** Docker-Container

**Updated from an older Teampass or fresh install:** fresh install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

#### Web server error log
```
teampass_1  | 10.0.2.2 - - [18/Dec/2018:15:55:58 +0000] "GET /api/index.php/info/version?apikey=GJasnRfkX8SY897S5xJ7CFuEM2HSYrR4yr48hde HTTP/1.1" 301 178 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
teampass_1  | 2018/12/18 15:56:39 [info] 28#28: *115 client closed connection while waiting for request, client: 10.0.2.2, server: 0.0.0.0:80
teampass_1  | 2018/12/18 15:56:39 [info] 28#28: *116 client closed connection while waiting for request, client: 10.0.2.2, server: 0.0.0.0:80
```

### Aditional information
When looking at previous issues and possible solutions, the latest commit on Dockerfile for this issue is not working properly:

From: https://github.com/nilsteampassnet/TeamPass/issues/2100

```
RUN sed -i '/^}/i \
        location /api/ {\
                try_files $uri $uri/ /api/index.php?$args;\
        }' /etc/nginx/sites-enabled/default.conf
```

when i take a look at the file "/etc/nginx/sites-enabled/default.conf" in container, it only contains 

`location /api/ {          try_files  / /api/index.php?;  }`

It seems that the variables from the change in Dockerfile need to be escacaped, otherwise they are empty variables.

However even changing it manually and restarting the container, i always get a 301...

Any help would be apreciated.
