### ISSUE TITLE
Unable to edit entry or copy password

### ISSUE THREAD

**Issue by jeffsuncorp** [nilsteampassnet/TeamPass#3897]
### Steps to reproduce
1. Unable to consistently reproduce

### Expected behaviour
Users should be able to view/copy password as well as view entry 

### Actual behaviour
Not all users, but multiple users can not view/edit entry or view copy/password.
Password is blank.
Have deleted users multiple times and have had users regenerate keys but still no luck.

As can bee seen in the logs below, it appears teampass is having an issue decrypting password for those particular accounts.
It feels like old keys are being used but can not put my finger on it.

### Server configuration
**Operating system**: Oracle Linux 9

**Web server:** httpd-2.4.53-11.0.1.el9_2.5.x86_64

**Database:** Percona Mysql 8.0.33

**PHP version:** PHP 8.0.27

**Teampass version:**  3.10.0

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**

global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/TeamPass/teampass',
    'cpassman_url' => 'https://<..>/teampass',
    'favicon' => 'https://<..>/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/TeamPass/teampass/upload',
    'path_to_files_folder' => '/var/www/html/TeamPass/teampass/files',
    'url_to_files_folder' => 'https://<..>.au/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.0.10',
    'ldap_mode' => '1',
    'ldap_type' => 'OpenLDAP',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'samaccountname',
    'ldap_ssl' => '1',
    'ldap_tls' => '1',
    'ldap_search_base' => '0',
    'ldap_port' => '636',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' =>
    'custom_login_text' =>
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1688448329',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '<..>',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '100',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '30mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '120',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/TeamPass/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => 'bne-util-log-central',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '1',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Australia/Brisbane',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' =>
    'admin_2fa_required' => '0',
    'password_overview_delay' => '2',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '1',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '(objectCategory=Person)',
    'ldap_bdn' =>
    'ldap_hosts' =>
    'ldap_password' =>
    'ldap_username' =>
    'api_token_duration' => '60',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '1',
    'upgrade_timestamp' => '1691040329',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '',
    'ldap_guid_attibute' => 'uid',
    'sending_emails_job_frequency' => '2',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'users_personal_folder_task' => 'daily;03:47',
    'clean_orphan_objects_task' => 'daily;15:17',
    'purge_temporary_files_task' => 'daily;23:42',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => 'hourly;16:32',
    'rebuild_config_file_task' => 'daily;05:48',
);

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```
```
==> /var/log/php-fpm/www-error.log <==
[10-Oct-2023 12:54:21 Australia/Brisbane] PHP Fatal error:  Uncaught TypeError: base64_encode(): Argument #1 ($string) must be of type string, bool given in /var/www/html/TeamPass/teampass/sources/main.functions.php:2789
Stack trace:
#0 /var/www/html/TeamPass/teampass/sources/main.functions.php(2789): base64_encode()
#1 /var/www/html/TeamPass/teampass/sources/items.queries.php(4173): doDataDecryption()
#2 {main}
  thrown in /var/www/html/TeamPass/teampass/sources/main.functions.php on line 2789
```
```
==> /var/log/httpd/teampass_access.log <==
10.44.31.1 - - [10/Oct/2023:12:54:21 +1000] "POST /teampass/sources/items.queries.php HTTP/1.0" 500 3 "https://<..>/teampass/index.php?page=items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

![Screenshot 2023-10-10 at 1 30 34 pm](https://github.com/nilsteampassnet/TeamPass/assets/14919686/0fa40f87-2f14-4409-9338-dc8fe8127651)

**Comment by rafa-ga** [comment]
I've been fighting with this issue a couple of weeks but it happens only with some LDAP users. At this moment all the local ones are ok.

**Comment by jeffsuncorp** [comment]
Thanks for confirming that it is not only me. And you are correct it is only random LDAP users.

**Comment by jeffsuncorp** [comment]
I have a test user that I use and fails. It has the special character  @  . Will test with different special character.

**Comment by rafa-ga** [comment]
> @jeffsuncorp @rafa-ga THank you for sharing. Wondering if it could come from a special character in the user's password. I will investigate. In the meantime would it be possible to ask the user what kind of special characters contain his password?

I'm using 3 accounts (1 personal + 2 test). Mine has only numbers and letters but yeah, the test accounts have both the same characteristics as mine plus "-". Our AD policies does not allow "simple" passwords since 2-3 months but I'll try to circumvent it.

Kind regards.

**Comment by jeffsuncorp** [comment]
With my test account I tested multiple iterations of passwords from LDAP. Still no luck.
When using the special character "~" for eg: "RandomPassWord~~~" it fails (even though I have that in my personal account's password and it works)
Also tried "RandomPassWord1234" and it failed
Unable to test just letters as AD policy won't let me.

**Comment by rafa-ga** [comment]
I've tried changing the password deleting the symbols and now it's working one of the two test accounts I created (the other one I haven't tried). Will keep testing and reporting here.

**Comment by jeffsuncorp** [comment]
I was able to get my AD Admin to create a password without special characters or numbers for the test account and still had no luck.
In addition, today another user had the same issue arise even though he has had no changes to his account.

**Comment by nilsteampassnet** [comment]
Thank you for your inputs.
I did also a lot of tests with several kind of user auth password and could not reproduce this.
It must be related a context I don't have in place.
Can you tell me if you are using most recent commit?
If not, please try to upgrade so that we are on same level of comparison.

**Comment by jeffsuncorp** [comment]
@nilsteampassnet Thanks for sticking with me here.
I am not on the latest commit but I did try a commit from a week or so ago.I will install the latest.

With regards to the new occurrence from an existing user, he stated:
"I logged in and it asked me for an encryption key, I then generated new keys and waited for the construction to finish. After it finished I could no longer view passwords"

It is Friday night here so probably won't be able to get back to you until Monday morning.

**Comment by nilsteampassnet** [comment]
I could reproduce the defect ... it occurs while generating new keys and impacts only personal items in some cases.
I will first fix this root cause and then handle the way to generate back the personal passwords.

**Comment by nilsteampassnet** [comment]
Have provided a fix.
PLease update.
Ask your user to reperform "generating new keys" action.

**Comment by jeffsuncorp** [comment]
Thank you for your persistence. I will update first thing Monday and get back to you.

**Comment by jeffsuncorp** [comment]
Have spent considerable time today trying to debug this in two environments, which resulted in different issues in both environments
 
**Prod Environment**

- Applied ('TP_VERSION_MINOR', '78');
- When logging in I am prompted with yellow popup bottom right corner with “seems your password has changed and team-pass requires it to encrypt your master private key”
- I regenerate new keys
- After waiting for new keys to be generated I login again but it continually prompts as above on every entry that I view/edit
- Had to roll back the prod instance

**Dev Environment**

- I then built a new Dev environment
- Was able to replicate “blank password issue” after key generation
- Upgraded to: ('TP_VERSION_MINOR', '78');
- Prompted to regenerate keys due to password change
- Did this but now account (tested with two accounts) sits at Account in construction (0)% for at least an hour. Have tried deleting users and creating new but no success

Scheduler runs fine without errors
In the teampass_user table both accounts are in the state
               **_special: generate-keys**

mysql> select * from teampass_processes_tasks where process_id = '16';
+--------------+------------+------------+------------+-------------+----------------------------------------+-------------------+----------------+----------------------+
| increment_id | process_id | created_at | updated_at | finished_at | task                                   | system_process_id | is_in_progress | sub_task_in_progress |
+--------------+------------+------------+------------+-------------+----------------------------------------+-------------------+----------------+----------------------+
|           57 |         16 | 1697434109 | NULL       | NULL        | {"step":"step0","index":0,"nb":"100"}  |              NULL |              0 |                    0 |
|           58 |         16 | 1697434109 | NULL       | NULL        | {"step":"step10","index":0,"nb":"100"} |              NULL |              0 |                    0 |
|           59 |         16 | 1697434109 | NULL       | NULL        | {"step":"step20","index":0,"nb":"100"} |              NULL |              0 |                    0 |
|           60 |         16 | 1697434109 | NULL       | NULL        | {"step":"step30","index":0,"nb":"100"} |              NULL |              0 |                    0 |
|           61 |         16 | 1697434109 | NULL       | NULL        | {"step":"step40","index":0,"nb":"100"} |              NULL |              0 |                    0 |
|           62 |         16 | 1697434109 | NULL       | NULL        | {"step":"step50","index":0,"nb":"100"} |              NULL |              0 |                    0 |
|           63 |         16 | 1697434109 | NULL       | NULL        | {"step":"step60","index":0,"nb":"100"} |              NULL |              0 |                    0 |
+--------------+------------+------------+------------+-------------+----------------------------------------+-------------------+----------------+----------------------+
7 rows in set (0.00 sec)

Any help would be appreciated.

**Comment by nilsteampassnet** [comment]
@jeffsuncorp 
Thanks for this.
Can you please provide the results of query `select * from teampass_processes where increment_id = '16';` ?

**Comment by jeffsuncorp** [comment]
```
mysql> select * from teampass_processes where increment_id = '16'\G;
*************************** 1. row ***************************
  increment_id: 16
    created_at: 1697434109
    updated_at:
   finished_at:
    process_id: NULL
  process_type: create_user_keys
        output:
     arguments: {"new_user_id":10000004,"new_user_pwd":"","new_user_code":"def502002efccdcec73be44169a414e269c09c0b81cd31ac25cbefe41e25de17449519272d3a715769a9932b397b2dd52209f8554b3b41415130e29db165416fbf85ff84bf423352cf4c901ed438336363f40c0063853b0eb43f451f4a7e6973baed2990","owner_id":10000001,"creator_pwd":"def50200ff2bb39d669c38753b3f5f61d8d4fad1e278a625711975348bc88f78a93355e1c8daa0eac836d38c6466b6393bc2a8dc571b0344dbedc46ad4c15034289b03ba94328316eb7770ee527b03fdd4cc4ec12bd4ed18f87ddc2e30b175eae","email_body":"Hello #lastname#,<br><br>This is a generated email from Teampass passwords manager.<br><br>Following code is expected next time using Teampass:<br><br><b>#code#<\/b><br><br><br>Cheers","send_email":1}
is_in_progress: 0
    started_at: NULL
       item_id: NULL
1 row in set (0.00 sec)
```

**Comment by nilsteampassnet** [comment]
@jeffsuncorp 

It seems the cron job for Teampass scheduler is not starting.
Check on your server if the cron is working with the same user as php

**Comment by jeffsuncorp** [comment]
Yes it is. Have double checked it a hundred times.. Will check it again though. I have also run the scripts manually as well
```
[root@bne-dev-teampass 16:58:10 /var/tmp/TeamPass/includes ]# tail -5 /var/log/cron
Oct 16 17:01:01 bne-dev-teampass CROND[2175188]: (root) CMDEND (run-parts /etc/cron.hourly)
Oct 16 17:01:01 bne-dev-teampass CROND[2175209]: (apache) CMD (/usr/bin/php /var/www/html/TeamPass/teampass/sources/scheduler.php >> /var/log/teampass-scheduler.log 2>&1 #Teampass scheduler)
Oct 16 17:01:01 bne-dev-teampass CROND[2175189]: (apache) CMDEND (/usr/bin/php /var/www/html/TeamPass/teampass/sources/scheduler.php >> /var/log/teampass-scheduler.log 2>&1 #Teampass scheduler)
Oct 16 17:02:01 bne-dev-teampass CROND[2175229]: (apache) CMD (/usr/bin/php /var/www/html/TeamPass/teampass/sources/scheduler.php >> /var/log/teampass-scheduler.log 2>&1 #Teampass scheduler)
Oct 16 17:02:01 bne-dev-teampass CROND[2175219]: (apache) CMDEND (/usr/bin/php /var/www/html/TeamPass/teampass/sources/scheduler.php >> /var/log/teampass-scheduler.log 2>&1 #Teampass scheduler)
```
```
[apache@bne-dev-teampass teampass]$ for i in scripts/*php; do ls ${i} ; done
scripts/background_tasks___do_calculation.php
scripts/background_tasks___functions.php
scripts/background_tasks___items_handler.php
scripts/background_tasks___sending_emails.php
scripts/background_tasks___user_keys_creation.php
scripts/background_tasks___user_task.php
scripts/task_maintenance_clean_orphan_objects.php
scripts/task_maintenance_purge_old_files.php
scripts/task_maintenance_rebuild_config_file.php
scripts/task_maintenance_reload_cache_table.php
scripts/task_maintenance_users_personal_folder.php
[apache@bne-dev-teampass teampass]$ for i in scripts/*php; do /usr/bin/php ${i} ; done
PHP Parse error:  syntax error, unexpected token "array", expecting variable in /var/www/html/TeamPass/teampass/includes/libraries/Symfony/Component/Process/Messenger/RunProcessMessage.php on line 20
```

**Comment by nilsteampassnet** [comment]
@jeffsuncorp 

The file that is executed by the cron is `sources/scheduler.php`.
Can you please launch it too from your shell?

The thing is that the task in DB has the field `started_at` set to NULL which means that this task has not be initiated.
So if the cron job is running then it means an error that has to be logged somewhere on the server.

**Comment by jeffsuncorp** [comment]
It all looks ok, must be something going on with my env if you've never seen this before
```
[apache@bne-dev-teampass teampass]$ which php
/usr/bin/php
[apache@bne-dev-teampass teampass]$ /usr/bin/php -version
PHP 8.0.27 (cli) (built: Jan  3 2023 16:17:26) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.27, Copyright (c), by Zend Technologies
[apache@bne-dev-teampass teampass]$  /usr/bin/php /var/www/html/TeamPass/teampass/sources/scheduler.php
[apache@bne-dev-teampass teampass]$
```

**Comment by jeffsuncorp** [comment]
@nilsteampassnet I agree. 
I assume you are wanting the apache logs not nginx?
There are no apache (or php-fpm) error logs worth noting. We do proxy through nginx but the logs look ok there as well.
I will investigate this further tomnorrow as it is late where I am.
Thanks again for your help

**Comment by david-szabo97** [comment]
We have the same problem. Fresh install using Docker Compose. Created two users with a shared role and folder. Created one with each user and they can't copy/view the other's password. After doing a "Generate new keys", it works as expected. But newly created/edit items don't work until generating new keys again.

**Comment by nilsteampassnet** [comment]
@david-szabo97 
Sh***, my fault, I did a mistake in the algorithm logic!
I have to fix this

**Comment by nilsteampassnet** [comment]
@david-szabo97 

Should be fixed in lastest commit.
I had implemented an inverse logic in an "IF statement".

**Comment by jeffsuncorp** [comment]
@nilsteampassnet 

Should probably make a new issue, but decided to add to the thread.  
I gave up with trying to debug the "Account in construction %0" issue so went for clean install with latest version
```
/var/www/html/TeamPass ]# grep VERSION teampass/includes/config/include.php
define('TP_VERSION', '3.0.10');
define('TP_VERSION_MINOR', '81');
```
Unfortunately I can't even get a clean install ( have completed many installs before).
Checked all logs and database tables but could not find any issue. Tried install multiple times but to no avail.
"At least one task has failed .. Please correct and relaunch"


![image](https://github.com/nilsteampassnet/TeamPass/assets/14919686/6798ba95-56d1-4ef5-a1ec-c3bcf702381d)

**Comment by jeffsuncorp** [comment]
@nilsteampassnet Sorry to disturb you but I'm not having any luck with any clean installs from the latest versions, as  outlined above. 

Have been trying everything, and trying to understand the code as best I can.

It looks like these checks are failing and most likely causing the install to fail
 
```
[{"error" : "Duplicate key name \"object_id_idx\"", "index" : "36", "multiple" : "true", "table" : "sharekeys_logs"}]
[{"error" : "Duplicate key name \"object_id_idx\"", "index" : "35", "multiple" : "true", "table" : "sharekeys_items"}]

Looked in the code and could not find why i'm getting duplicate key name error. 

Any pointers would be appreciated.

**Comment by jeffsuncorp** [comment]
@nilsteampassnet I see you have put a lot of work in over the weekend, thanks. I have got a dev install working, will try prod later today. 
Just a heads up, I got this error when upgrading from 3.09 -->  3.0.10.83

ERROR: An error appears when adding field keys_recovery_time to table users! You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT NULL DEFAULT' at line 1!



Work around was to edit upgrade_run_3.0.php with the below appeared to work and got the dev version installed.. Will let you know how I go with prod 
```
$res = addColumnIfNotExist(
    $pre . 'users',
    'keys_recovery_time',
    "NULL DEFAULT NULL;"
);
```
Replaced with
```
$res = addColumnIfNotExist(
     $pre . 'users',
     'keys_recovery_time',
     "VARCHAR(500) NULL DEFAULT NULL;"
);
```
Current version loaded 3.0.10.83

**Comment by jeffsuncorp** [comment]
@nilsteampassnet 
Tried to do the prod upgrade but had no luck stangely enough. It does not progress. 
If I use incorrect login data it fails with user unknown.
Nothing in the web logs.



![image](https://github.com/nilsteampassnet/TeamPass/assets/14919686/c2553286-2748-4d53-9e83-6f3398a43952)

**Comment by nilsteampassnet** [comment]
@jeffsuncorp 
What's in your apache error log file?

**Comment by jeffsuncorp** [comment]
@nilsteampassnet 
I've already rolled back to the snapshot as it was the prod site so the logs are gone, but there were no errors in the apache logs or php-fpm logs.

**Comment by jeffsuncorp** [comment]
@nilsteampassnet 
Hi, Updated to latest "87" .. Am able to install and existing working users are OK. Thanks.
Broken users are able to download keys but can not re-generate keys "0%  Progress" similar to what I was having earlier on.
cronjob is running as can be seen below with use_build_cache_tree is run but  create_user_keys never starts.
Ran scheduler manually, no errors. No errors in log files or in console.
Have tried deleting users and re-creating without luck, tested on dev & prod install.
@Len16-53 are you able to install and test? Just want to make sure it is not a "me" issue.
```
*************************** 140. row ***************************
  increment_id: 164
    created_at: 1698116956
    updated_at: 1698117001
   finished_at: 1698117001
    process_id: NULL
  process_type: user_build_cache_tree
        output:
     arguments: {"user_id":10000028}
is_in_progress: -1
    started_at: 1698117001
       item_id: NULL
*************************** 141. row ***************************
  increment_id: 165
    created_at: 1698117302
    updated_at:
   finished_at:
    process_id: NULL
  process_type: create_user_keys
        output:
     arguments: {"new_user_id":10000025,"new_user_pwd":"def50200eae6f11fc54d6cce98b1cb82fd8e6a428b31ab0bde45b28af93680b1216f3f5b07995e2e2795726076fa9a8710d267593d7add7f40448bcd8b1199378cff87f2799651e9c1462899f6a30e747ed5cf5dd5454356fba2d7a13050697a","new_user_code":"def50200f4f34c7a20f092bb8c93e90f526202559d5faba0af2e54e8732ed93146cb06eabe285621cb47539a69264b5eb1087ba3a900509a3a2446eb901c71809bc5f23856a6992bbf60aeb5d97c4591d3e5c3595f039a6e04db210b52c5cadd","owner_id":9999997,"creator_pwd":"def50200e3b813500b06021769320e446b3645093fcef799b1e1fe01c26238cbf4e0a18f32e85d0897a62cc2692240d391803e68f82dfc97bab4ac538d12dc99e5208334c789b5cb6b2523208cca4beffa1e82d2d290f28b0d8f1ba1bf94514777a1dbf66e1b328ea618d04509","send_email":1,"otp_provided_new_value":1,"email_body":"Hello #lastname#,<br><br>This is a generated email from Teampass passwords manager.<br><br>Your Teampass account is fully ready.<br><br>Cheers","user_self_change":1}
is_in_progress: 0
    started_at: NULL
       item_id: NULL
141 rows in set (0.00 sec)
```

**Comment by nilsteampassnet** [comment]
@jeffsuncorp 

Thank you for your inputs.
I don't understand what is happening here.

You mean that even if you execute through a shell the file background_tasks___user_keys_creation.php, nothing happens, correct?

What if you execute query
````
SELECT *
      FROM teampass_processes
      WHERE is_in_progress = 0 AND finished_at = "" AND process_type =  'create_user_keys'
      ORDER BY increment_id ASC;
```
It should return the record 165

**Comment by jeffsuncorp** [comment]
It must be local to me if no-one else is seeing it.. I do get an error running background_tasks___user_keys_creation.php 

```
[root@bne-prd-teampass 17:20:59 /var/www/html/TeamPass/teampass ]# /usr/bin/php scripts/background_tasks___user_keys_creation.php
PHP Parse error:  syntax error, unexpected token "array", expecting variable in /var/www/html/TeamPass/teampass/includes/libraries/Symfony/Component/Process/Messenger/RunProcessMessage.php on line 20
```
```
  increment_id: 165
    created_at: 1698117302
    updated_at:
   finished_at:
    process_id: NULL
  process_type: create_user_keys
        output:
     arguments: {"new_user_id":10000025,"new_user_pwd":"def50200eae6f11fc54d6cce98b1cb82fd8e6a428b31ab0bde45b28af93680b1216f3f5b07995e2e2795726076fa9a8710d267593d7add7f40448bcd8b1199378cff87f2799651e9c1462899f6a30e747ed5cf5dd5454356fba2d7a13050697a","new_user_code":"def50200f4f34c7a20f092bb8c93e90f526202559d5faba0af2e54e8732ed93146cb06eabe285621cb47539a69264b5eb1087ba3a900509a3a2446eb901c71809bc5f23856a6992bbf60aeb5d97c4591d3e5c3595f039a6e04db210b52c5cadd","owner_id":9999997,"creator_pwd":"def50200e3b813500b06021769320e446b3645093fcef799b1e1fe01c26238cbf4e0a18f32e85d0897a62cc2692240d391803e68f82dfc97bab4ac538d12dc99e5208334c789b5cb6b2523208cca4beffa1e82d2d290f28b0d8f1ba1bf94514777a1dbf66e1b328ea618d04509","send_email":1,"otp_provided_new_value":1,"email_body":"Hello #lastname#,<br><br>This is a generated email from Teampass passwords manager.<br><br>Your Teampass account is fully ready.<br><br>Cheers","user_self_change":1}
is_in_progress: 0
    started_at: NULL
       item_id: NULL
3 rows in set (0.00 sec)
```

**Comment by jeffsuncorp** [comment]
It must be local to me if noone else is seeing it.. i do get an error running background_tasks___user_keys_creation
```
[apache@bne-prd-teampass teampass]$ /usr/bin/php scripts/background_tasks___user_keys_creation.php
PHP Parse error:  syntax error, unexpected token "array", expecting variable in /var/www/html/TeamPass/teampass/includes/libraries/Symfony/Component/Process/Messenger/RunProcessMessage.php on line 20
```
```
*************************** 3. row ***************************
  increment_id: 165
    created_at: 1698117302
    updated_at:
   finished_at:
    process_id: NULL
  process_type: create_user_keys
        output:
     arguments: {"new_user_id":10000025,"new_user_pwd":"def50200eae6f11fc54d6cce98b1cb82fd8e6a428b31ab0bde45b28af93680b1216f3f5b07995e2e2795726076fa9a8710d267593d7add7f40448bcd8b1199378cff87f2799651e9c1462899f6a30e747ed5cf5dd5454356fba2d7a13050697a","new_user_code":"def50200f4f34c7a20f092bb8c93e90f526202559d5faba0af2e54e8732ed93146cb06eabe285621cb47539a69264b5eb1087ba3a900509a3a2446eb901c71809bc5f23856a6992bbf60aeb5d97c4591d3e5c3595f039a6e04db210b52c5cadd","owner_id":9999997,"creator_pwd":"def50200e3b813500b06021769320e446b3645093fcef799b1e1fe01c26238cbf4e0a18f32e85d0897a62cc2692240d391803e68f82dfc97bab4ac538d12dc99e5208334c789b5cb6b2523208cca4beffa1e82d2d290f28b0d8f1ba1bf94514777a1dbf66e1b328ea618d04509","send_email":1,"otp_provided_new_value":1,"email_body":"Hello #lastname#,<br><br>This is a generated email from Teampass passwords manager.<br><br>Your Teampass account is fully ready.<br><br>Cheers","user_self_change":1}
is_in_progress: 0
    started_at: NULL
       item_id: NULL
3 rows in set (0.00 sec)
```
